<style>
.ss-container {
margin: 2em auto auto auto;
width: 490px;
background:#FFF;
border: 1px solid;
border-color: #CCC #999 #999 #CCC;

}
element.style {
}
Matched CSS Rules
.ss-resp-card {
background-color: white;
padding: 1em;
padding-bottom: 0.5em;
border: 1px solid;
border-color: #CCC #999 #999 #CCC;
font-family:Verdana, Geneva, sans-serif;
font-size: 13px;
color: #222;
}
element.style {
}
.ss-break {
border: 0;
background-color: #CCC;
height: 1px;
margin-bottom: 0.6em;
margin-top: 25px;
width:95%;
}
.ss-footer {
position: relative;
height: 26px;
}


</style>
<body style="background-color: #EBEBEB;">
<div class="ss-container">
	<div class="ss-resp-card">
    <p><font size="4"><b>Anda Telah Berhasil Mendaftar</b></font>
    <br>
    Your response has been recorded.<br><br>
        </div>
	<hr class="ss-break">
	<div class="ss-footer"><div class="ss-footer-txt"><a class="ss-actions-link" href="/register">  Kembali Ke Login</a></div></div>
</div>
</body>
