<table border="1">
	<tr>
		<td>realname</td>
		<td>address</td>
		<td>city</td>
		<td>state</td>
		<td>contact</td>
		<td>phone0</td>
		<td>tradingname</td>
		<td>email</td>
		<td colspan="2">action</td>
	</tr>
    
	<?php foreach($this->register as $register){ ?>
	<tr>
		<td><?php echo $this->escape($register->realname);?></td>
		<td><?php echo $this->escape($register->address);?></td>
		<td><?php echo $this->escape($register->city);?></td>
		<td><?php echo $this->escape($register->state);?></td>
		<td>aa</td>
		<td>aa</td>
		<td><?php echo $this->escape($register->tradingname);?></td>
		<td><?php echo $this->escape($register->email);?></td>
		<td><form method="post" action="update">
	<input type="hidden" value="<?php echo $this->escape($register->id);?>"  name="id"/><input name="" type="submit" value="approve" /></form></td>
		<td><form method="post" action="detail">
	<input type="hidden" value="<?php echo $this->escape($register->id);?>"  name="id2"/><input name="" type="submit" value="detail" /></form></td>
	</tr>
<?php } ?>
</table>